remote_theme: pmarsceill/just-the-docs

markdown: kramdown
lang: en
domain: docs.wela.io
title: Wela

google_font_family: Titillium+Web:300,400,600,700|Open+Sans:300,400,600,700


plugins:
  - jekyll-seo-tag
